<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNAGgOrR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNAGgOrR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNAGgOrR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNAGgOrR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNAGgOrR\App_KernelDevDebugContainer([
    'container.build_hash' => 'NAGgOrR',
    'container.build_id' => '278ecc6e',
    'container.build_time' => 1651672697,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNAGgOrR');
